"use client";

import { useLanguage } from "@/lib/i18n/LanguageContext";
import SqlFormatterClient from "./SqlFormatterClient";
import FAQSection from "@/components/ui/FAQSection";

export default function SqlFormatterContent() {
    const { locale } = useLanguage();
    const isVi = locale === "vi";

    const faqItems = [
        {
            question: isVi ? "SQL Formatter là gì?" : "What is an SQL Formatter?",
            answer: isVi
                ? "SQL Formatter là công cụ trực tuyến giúp làm đẹp, căn chỉnh lề và chuẩn hóa các câu lệnh truy vấn SQL phức tạp để dễ đọc, dễ bảo trì và tìm lỗi hơn."
                : "An SQL Formatter is a developer utility that beautifies, indents, and standardizes complex SQL queries, making them easy to read, debug, and maintain.",
        },
        {
            question: isVi ? "Công cụ hỗ trợ những hệ quản trị cơ sở dữ liệu nào?" : "Which SQL dialects are supported?",
            answer: isVi
                ? "Công cụ hỗ trợ đa dạng các dialect phổ biến: Standard SQL (ANSI), PostgreSQL, MySQL, SQLite, Google BigQuery, MariaDB, SQL Server (T-SQL) và Oracle PL/SQL."
                : "The formatter supports Standard SQL (ANSI), PostgreSQL, MySQL, SQLite, Google BigQuery, MariaDB, Microsoft SQL Server (T-SQL), and Oracle PL/SQL.",
        },
        {
            question: isVi ? "Câu truy vấn SQL của tôi có được bảo mật không?" : "Is my SQL query data secure?",
            answer: isVi
                ? "Hoàn toàn an toàn 100%! Thuật toán định dạng SQL chạy trực tiếp trên trình duyệt bằng JavaScript, không có dữ liệu nào được lưu trữ hay gửi lên bất kỳ máy chủ nào."
                : "100% secure! The formatting engine executes purely on the client side inside your browser. No queries, table schemas, or database information are ever transmitted over the network.",
        },
    ];

    return (
        <div className='max-w-6xl mx-auto'>
            {/* Main Interactive Studio */}
            <SqlFormatterClient />

            {/* SEO Overview & Guides */}
            <section className='mt-16 space-y-8'>
                <div className='bg-white dark:bg-gray-800 rounded-2xl p-6 md:p-8 border border-gray-200 dark:border-gray-700 shadow-sm space-y-4'>
                    <h2 className='text-2xl font-bold text-gray-900 dark:text-gray-100'>
                        {isVi ? "Tại sao cần định dạng câu lệnh SQL?" : "Why Format Your SQL Queries?"}
                    </h2>
                    <p className='text-gray-600 dark:text-gray-400 leading-relaxed'>
                        {isVi
                            ? "Khi phát triển phần mềm, các câu lệnh truy vấn SQL thường được sinh tự động bởi ORM (như Prisma, Hibernate, Entity Framework) hoặc viết nhanh trên một dòng dài hàng nghìn ký tự. Việc định dạng lại cấu trúc bảng, các mệnh đề JOIN, WHERE, GROUP BY và CTE giúp các kỹ sư cơ sở dữ liệu dễ dàng phát hiện điểm nghẽn hiệu năng (bottleneck), thiếu chỉ mục (index) hoặc lỗi logic trong câu lệnh."
                            : "In enterprise software engineering, SQL queries are frequently generated by ORMs or written hastily in a single long string. Formatting and beautifying clauses (SELECT, FROM, WHERE, JOIN, GROUP BY) enables backend engineers and DBAs to quickly spot syntax issues, missing indexes, and optimization bottlenecks."}
                    </p>

                    <div className='grid grid-cols-1 md:grid-cols-3 gap-4 pt-4'>
                        <div className='p-4 rounded-xl bg-gray-50 dark:bg-gray-900/60 border border-gray-200 dark:border-gray-700'>
                            <div className='text-xl mb-1'>🗄️</div>
                            <h3 className='font-bold text-sm text-gray-900 dark:text-gray-100 mb-1'>
                                {isVi ? "Đa Dialect CSDL" : "Multi-Dialect Support"}
                            </h3>
                            <p className='text-xs text-gray-500 dark:text-gray-400'>
                                {isVi ? "Tùy chỉnh ngữ pháp riêng cho PostgreSQL, MySQL, BigQuery, T-SQL, SQLite." : "Customized dialect rules for Postgres, MySQL, BigQuery, SQLite, and T-SQL."}
                            </p>
                        </div>
                        <div className='p-4 rounded-xl bg-gray-50 dark:bg-gray-900/60 border border-gray-200 dark:border-gray-700'>
                            <div className='text-xl mb-1'>🔤</div>
                            <h3 className='font-bold text-sm text-gray-900 dark:text-gray-100 mb-1'>
                                {isVi ? "Chuẩn Hóa Chữ Hoa / Thường" : "Uppercase Keywords"}
                            </h3>
                            <p className='text-xs text-gray-500 dark:text-gray-400'>
                                {isVi ? "Tự động viết hoa toàn bộ từ khóa SQL (SELECT, FROM, WHERE) theo tiêu chuẩn sạch." : "Enforce clean uppercase keywords according to industry SQL style guides."}
                            </p>
                        </div>
                        <div className='p-4 rounded-xl bg-gray-50 dark:bg-gray-900/60 border border-gray-200 dark:border-gray-700'>
                            <div className='text-xl mb-1'>🗜️</div>
                            <h3 className='font-bold text-sm text-gray-900 dark:text-gray-100 mb-1'>
                                {isVi ? "Nén SQL 1 Dòng (Minify)" : "SQL Minification"}
                            </h3>
                            <p className='text-xs text-gray-500 dark:text-gray-400'>
                                {isVi ? "Dễ dàng nén câu lệnh thành chuỗi 1 dòng gọn nhẹ để nhúng vào code backend." : "Quickly strip comments and compress whitespace to embed queries in source code."}
                            </p>
                        </div>
                    </div>
                </div>

                {/* FAQ Section */}
                <FAQSection locale={locale} faqs={faqItems} />
            </section>
        </div>
    );
}
