export const searchTopics = [
    "latest AI advancements",
    "Next.js 14 features",
    "server components vs client components",
    "React 19 new hooks",
    "state of JavaScript 2026",
    "best frontend frameworks",
    "Tailwind CSS vs. CSS-in-JS",
    "monorepo architecture benefits",
    "Vercel deployment guide",
    "optimizing web performance",
    "TypeScript best practices",
    "GraphQL vs REST API",
    "Docker for web developers",
    "Kubernetes basics",
    "CI/CD pipeline setup",
    "automated testing with Playwright",
    "web accessibility standards",
    "progressive web apps (PWA) tutorial",
    "WebAssembly use cases",
    "Bun vs. Node.js performance",
    "Rust for web development",
    "building micro-frontends",
    "serverless functions explained",
    "edge computing in web dev",
    "history of the internet",
];
